version: "3.9"
services:

  oracle:
    image: "doctorkirk/oracle-19c"
    ports:
      - "1521:1521"
    volumes: 
       - desktop_oracle-volume:/opt/oracle/oradata
    environment:
      - ORACLE_SID:ORCLCDB
      - ORACLE_PWD:password

  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - flask-volume:/opt/flask/flaskdata
    depends_on:
      oracle:
        condition: service_started
    command: ["python", "controllers/app.py"]
       
volumes:
  desktop_oracle-volume:
    external: true 
  flask-volume:
    external: true 
