version: "3.9"
services:

  oracle:
    image: "doctorkirk/oracle-19c"
    ports:
      - "1521:1521"
    volumes: 
        - desktop_oracle-volume:/opt/oracle/oradata
    environment:
      - ORACLE_SID:ORCLCDB
      - ORACLE_PWD:password

  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/backend
    depends_on:
      - oracle
    command: ["../wait-for.sh", "oracle:1521", "--", "python", "app.py"]
       
volumes:
  desktop_oracle-volume:
    external: true  
